from .inventory import _inventory_monster_get, _inventory_monster_set, _inventory_monster_new, _inventory_monster_get_user_monsters, _inventory_monster_get_calculated_health_points, _inventory_monster_get_calculated_attack_power, _inventory_monster_get_calculated_defense_power, _inventory_monster_use_potion, _inventory_monster_tick

inventory_monster_get = _inventory_monster_get
inventory_monster_set = _inventory_monster_set
inventory_monster_new = _inventory_monster_new
inventory_monster_get_user_monsters = _inventory_monster_get_user_monsters
inventory_monster_get_calculated_health_points = _inventory_monster_get_calculated_health_points
inventory_monster_get_calculated_attack_power = _inventory_monster_get_calculated_attack_power
inventory_monster_get_calculated_defense_power = _inventory_monster_get_calculated_defense_power
inventory_monster_use_potion = _inventory_monster_use_potion
inventory_monster_tick = _inventory_monster_tick
