from .potion import _potion_get, _potion_set, _potion_new, _potion_get_type_generic, _potion_is_type_definite, _potion_is_type_indefinite, _potion_get_calculated_definite_base_amount, _potion_get_calculated_definite_multiplier_amount, _potion_get_calculated_indefinite_amount

potion_get = _potion_get
potion_set = _potion_set
potion_new = _potion_new
potion_get_type_generic = _potion_get_type_generic
potion_is_type_definite = _potion_is_type_definite
potion_is_type_indefinite = _potion_is_type_indefinite
potion_get_calculated_definite_base_amount = _potion_get_calculated_definite_base_amount
potion_get_calculated_definite_multiplier_amount = _potion_get_calculated_definite_multiplier_amount
potion_get_calculated_indefinite_amount = _potion_get_calculated_indefinite_amount
